### ISSUE TITLE
[FEATURE REQUEST] Double Click Registration

### ISSUE THREAD

**Issue by JosTheDude** [Tobbesson/roccat-konepro-linux#1]
Heyo! Love the driver, was exactly what I was looking for. 

Roccat SWARM has a feature for configuring the double click registration and I was wondering if it was possible here? I'm unsure where you're finding the driver documentation to make the configurable settings you have since otherwise I'd attempt a PR.

**Comment by Tobbesson** [comment]
That setting doesn't make any changes to the mouse it only changes mouse property "Double click speed" in windows control panel.
Some brief research suggests that such a setting is dependent on distro.
https://bbs.archlinux.org/viewtopic.php?id=240001
https://askubuntu.com/questions/1176318/how-to-set-the-minimum-time-between-double-clicks
https://stackoverflow.com/questions/50868129/how-to-get-double-click-time-interval-value-programmatically-on-linux

Also I don't have any driver documentation I am only modifying the on-board memory by playing around with the roccat swarm settings and reviewing the packets sent with wireshark.

**Comment by JosTheDude** [comment]
You are awesome! And damn, didn't think about that.

You should consider messaging Roccat about their driver documentation -- they've sponsored Linux community maintained drivers (roccat-tools, now unmaintained) in the past. They may be willing to send it to you to simplify things and possibly officially list it

Thanks regardless! And the docs help a ton :D

**Comment by JosTheDude** [comment]
If anyone else has this issue, I followed this post to get the debounce/double click time set to 0 (good for Minecraft PvP, on Roccat Kone Pro)

https://www.reddit.com/r/linux_gaming/comments/or1g40/changing_mouse_debounce_time_on_arch_linux/
